#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=6
TOTAL_MINUTES=25

# This wizard writes nothing to .env on purpose. The only value it captures is
# a Postgres connection string with a password in it, this repository is
# public, and the two places it is actually needed — GitHub Actions and
# Streamlit Community Cloud — both store it themselves. Re-running therefore
# asks for it again, which is the safer trade.

banner "Deploy the GE16 dashboard (issues #7 and #9)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check the tools this needs" 2
say "Two things have to be true before anything else works."
say ""

if ! command -v gh >/dev/null 2>&1; then
  warn "The GitHub CLI (gh) is not installed."
  say "Install it with:  brew install gh"
  say "Then re-run this wizard."
  exit 1
fi
printf '  %s✓%s gh is installed\n' "$GREEN" "$RESET"

if ! gh auth status >/dev/null 2>&1; then
  warn "gh is installed but not logged in."
  say "Run:  gh auth login"
  say "Then re-run this wizard."
  exit 1
fi
GH_USER=$(gh api user --jq .login 2>/dev/null || echo "unknown")
printf '  %s✓%s gh is logged in as %s%s%s\n' "$GREEN" "$RESET" "$BOLD" "$GH_USER" "$RESET"

REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || echo "")
if [[ -z "$REPO" ]]; then
  warn "This directory is not a GitHub repository gh can see."
  say "Run this wizard from inside the live-political-analysis checkout."
  exit 1
fi
printf '  %s✓%s repository %s%s%s\n' "$GREEN" "$RESET" "$BOLD" "$REPO" "$RESET"
say ""

if [[ "$GH_USER" != "IlhamKassim" ]]; then
  warn "gh is authenticated as '$GH_USER', not IlhamKassim."
  note "You have two GitHub accounts on this machine. The secret must be set"
  note "on the account that owns $REPO, or the Actions runs will not see it."
  confirm "Carry on as $GH_USER anyway?" || {
    say "Switch with:  gh auth switch"
    exit 1
  }
fi

say "The workflow files and the deploy config are already committed."
note "If .github/workflows/ is not on your main branch yet, push it first —"
note "stages 3 and 4 trigger those workflows on GitHub, not locally."
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Neon — create the Postgres the pipeline writes to" 6
say "The pipeline currently writes a local SQLite file. GitHub Actions has no"
say "such file, so it needs a hosted database. Neon's free tier is enough:"
say "this project stores one row per day and 222 Baseline rows."
say ""
open_url "https://console.neon.tech/signup"
step "Sign up (choosing 'Continue with GitHub' is the fewest clicks)."
step "When it asks, create a project. Any name is fine — 'live-political-analysis'."
step "Pick the region closest to you; it does not matter for a daily job."
say ""
step "After the project is created you land on its dashboard, which shows a"
step "  'Connection string' box with a Copy button. Click it."
note "It looks like:  postgresql://user:PASSWORD@ep-something.aws.neon.tech/neondb?sslmode=require"
note "Paste it exactly as Neon gives it to you — no editing. The project"
note "rewrites the driver prefix itself."
say ""
ask_secret NEON_URL "Paste the Neon connection string (hidden):"

if [[ -z "${NEON_URL:-}" ]]; then
  warn "Nothing pasted. Re-run the wizard when you have the connection string."
  exit 1
fi
case "$NEON_URL" in
  postgres://*|postgresql://*) : ;;
  *) warn "That does not look like a Postgres URL (expected it to start with"
     warn "postgresql://). Check you copied the connection string and not the"
     warn "psql command line, then re-run."
     exit 1 ;;
esac
printf '  %s✓%s looks like a Postgres connection string\n' "$GREEN" "$RESET"

set_secret DATABASE_URL "$NEON_URL"
say ""
note "That is now a GitHub Actions secret. It is not written to disk anywhere"
note "in this repository, so keep the Neon tab open — stage 6 needs it again."
pause "Continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Load the GE15 Baseline into it" 4
say "The database is empty, and the pipeline refuses to run without the"
say "Baseline — the 222 GE15 Seat results every Projection is computed from."
say "One workflow does that, by hand, once."
say ""

if ! confirm "Trigger the 'Load Seat Baseline' workflow now?"; then
  SKIPPED+=("Run the 'Load Seat Baseline' workflow: gh workflow run bootstrap.yml")
  warn "Skipped. The pipeline will fail until this has run."
else
  if gh workflow run bootstrap.yml >/dev/null 2>&1; then
    printf '  %s✓%s triggered\n' "$GREEN" "$RESET"
    say "Waiting for it to finish (usually about a minute)..."
    sleep 8
    gh run watch "$(gh run list --workflow=bootstrap.yml --limit 1 --json databaseId --jq '.[0].databaseId')" --exit-status \
      && printf '  %s✓%s Baseline loaded — 222 Seats\n' "$GREEN" "$RESET" \
      || { warn "That run failed. Open the log below, fix it, and re-run this stage."
           gh run list --workflow=bootstrap.yml --limit 1
           SKIPPED+=("Re-run the Load Seat Baseline workflow once the failure is fixed") ; }
  else
    warn "Could not trigger the workflow."
    note "The usual cause is that .github/workflows/bootstrap.yml is not on the"
    note "default branch yet. Push it, then re-run this wizard."
    SKIPPED+=("Run the 'Load Seat Baseline' workflow")
  fi
fi
pause "Continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Prove the daily pipeline runs unattended" 5
say "This is issue #7's real acceptance test: the scheduled workflow running"
say "start to finish with nobody helping it, and a snapshot appearing after."
say ""
note "The schedule is 15:00 UTC — 23:00 in Malaysia, late enough in the"
note "Malaysian day that the snapshot covers the coverage it is dated for."
note "This run is the same workflow, triggered by hand so you needn't wait."
say ""
warn "It downloads the sentiment model on the first run, so expect 5-10"
warn "minutes. Later runs hit the cache and are much quicker."
say ""

if ! confirm "Trigger the daily pipeline now?"; then
  SKIPPED+=("Run the daily pipeline: gh workflow run daily.yml")
else
  if gh workflow run daily.yml >/dev/null 2>&1; then
    printf '  %s✓%s triggered\n' "$GREEN" "$RESET"
    sleep 8
    gh run watch "$(gh run list --workflow=daily.yml --limit 1 --json databaseId --jq '.[0].databaseId')" --exit-status \
      && printf '  %s✓%s the pipeline ran and stored a snapshot\n' "$GREEN" "$RESET" \
      || { warn "That run failed — see the log above."
           SKIPPED+=("Re-run the daily pipeline once the failure is fixed") ; }
  else
    warn "Could not trigger the workflow. Is .github/workflows/daily.yml pushed?"
    SKIPPED+=("Run the daily pipeline")
  fi
fi
pause "Continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Streamlit Community Cloud — create the app" 5
say "Now the public dashboard (issue #9). Community Cloud is free and"
say "redeploys on every push to main by itself."
say ""
open_url "https://share.streamlit.io/"
step "Sign in with GitHub and authorise it when asked."
note "It needs read access to $REPO to deploy from it."
say ""
step "Click 'Create app', then choose 'Deploy a public app from GitHub'."
say ""
say "Fill the form in exactly like this:"
printf '      %sRepository%s    %s\n' "$BOLD" "$RESET" "$REPO"
printf '      %sBranch%s        main\n' "$BOLD" "$RESET"
printf '      %sMain file%s     src/lpa/dashboard.py\n' "$BOLD" "$RESET"
say ""
note "Under 'Advanced settings', set Python version to 3.11 or newer."
note "Do not click Deploy yet — the next stage adds the database secret,"
note "and deploying without it shows an empty-database page."
pause "Form filled in?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Give the app its database, and deploy" 3
say "The dashboard reads the same Neon database the pipeline writes to."
say "Community Cloud has no environment variables — it has per-app secrets,"
say "in TOML — so the connection string goes in there."
say ""
step "Still in 'Advanced settings', find the 'Secrets' box."
step "Paste this one line, with your Neon string in the quotes:"
say ""
printf '      %sDATABASE_URL = "postgresql://...paste yours here..."%s\n' "$BOLD" "$RESET"
say ""
warn "The quotes are required — it is TOML, not a shell variable."
note "Your Neon string is still on the clipboard from stage 2, or in the"
note "Neon tab you left open."
say ""
step "Now click Deploy. The first build takes a few minutes."
pause "Deployed?"

say ""
ask APP_URL "Paste the public app URL (https://....streamlit.app):"
if [[ -n "${APP_URL:-}" ]]; then
  open_url "$APP_URL"
  say ""
  step "Check the page shows a Projection and a seat table — not a warning"
  step "  about an empty database."
  if confirm "Does the dashboard show the Projection?"; then
    printf '  %s✓%s issue #9 is done\n' "$GREEN" "$RESET"
  else
    warn "If it says there is no Baseline or no Projection, the app is"
    warn "reading a different database than the pipeline wrote to — check the"
    warn "DATABASE_URL secret in the Streamlit app settings matches Neon's."
    SKIPPED+=("Dashboard is deployed but not showing data — check its DATABASE_URL secret")
  fi
else
  SKIPPED+=("Confirm the deployed dashboard shows a Projection")
fi

finish

printf '  %sWhat happens now, without you:%s\n' "$BOLD" "$RESET"
note "  - 23:00 Malaysian time daily, the pipeline scrapes, scores and stores."
note "  - The dashboard reads that database, so it follows along by itself."
note "  - Pushing to main redeploys the dashboard."
printf '\n'
note "Watch a run:      gh run list --workflow=daily.yml"
note "Run it now:       gh workflow run daily.yml"
if [[ -n "${APP_URL:-}" ]]; then
  note "The dashboard:    $APP_URL"
fi
printf '\n'
